#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CondominioApp.Resource", IsApplication=true)]

namespace CondominioApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050000
			public const int colorPrimary = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int theme_devicedefault_background = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int windowBackground = 2131034113;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int chico = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int icon2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int logocondominio = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int tarjeta_credito = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080012
			public const int MyButton = 2131230738;
			
			// aapt resource value: 0x7f080011
			public const int btnIngresarLogin = 2131230737;
			
			// aapt resource value: 0x7f080008
			public const int btnMedioPago = 2131230728;
			
			// aapt resource value: 0x7f080000
			public const int getWeatherButton = 2131230720;
			
			// aapt resource value: 0x7f080002
			public const int getWeatherButton2 = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int getWeatherButton3 = 2131230724;
			
			// aapt resource value: 0x7f080006
			public const int getWeatherButton4 = 2131230726;
			
			// aapt resource value: 0x7f08000a
			public const int imageView1 = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int linearLayout1 = 2131230729;
			
			// aapt resource value: 0x7f08000b
			public const int linearLayout2 = 2131230731;
			
			// aapt resource value: 0x7f08000d
			public const int linearLayout3 = 2131230733;
			
			// aapt resource value: 0x7f08000e
			public const int linearLayout4 = 2131230734;
			
			// aapt resource value: 0x7f080010
			public const int linearLayout5 = 2131230736;
			
			// aapt resource value: 0x7f080001
			public const int textView1 = 2131230721;
			
			// aapt resource value: 0x7f080003
			public const int textView2 = 2131230723;
			
			// aapt resource value: 0x7f080005
			public const int textView3 = 2131230725;
			
			// aapt resource value: 0x7f080007
			public const int textView4 = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public const int txtContrasena = 2131230735;
			
			// aapt resource value: 0x7f08000c
			public const int txtUsuario = 2131230732;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Contenido = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MedioPago = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int Bienvenido = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int espacios = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int estacionamiento = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int favor = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int gastos = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ingrese = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int morosidad = 2130968582;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Custom = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int Theme_Custom1 = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int Theme_Custom2 = 2131165186;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
